//This header file was generated by ComBuilder on 17.03.2014 16:57:59

/**********************************************************************************
File Description:
This file contains the header of one SubMessage of the sensor Ultrasound.
For general sensor information see '../sensors/'UltrasoundSensor.h

All messages have to be understand by Nios2 and Linux-PC. Please use the flag
CENTRAL_ECU_BUILD to distinguish the different builds!

**********************************************************************************/


/**********************************************************************************
SubMessage Description:
Message contains the distance and a valid-flag.
**********************************************************************************/

#ifndef ULTRASOUNDDISTANCEMESSAGE_H_
#define ULTRASOUNDDISTANCEMESSAGE_H_

// Import Interfaces
#include "CarMessage.h"


class CUltrasoundDistanceMessage : public CCarMessage
{
public:
	CUltrasoundDistanceMessage();
	CUltrasoundDistanceMessage(alt_u8* pMessage, int iLength);
	virtual ~CUltrasoundDistanceMessage();
	void answerMessage(alt_32 iDistance);
	void doAction();
	bool getBytes(alt_u8* pMessage);
	alt_u32 getLength();

	alt_u16 getUiDistance() const {
		return m_uiDistance;
	}

	alt_u8 getUiDistanceValid() const {
		return m_uiDistanceValid;
	}

private:
	alt_u16 m_uiDistance;
	alt_u8 m_uiDistanceValid;

    void parseMessage(alt_u8 *pMessage, int iLength);

};

#endif /* ULTRASOUNDDISTANCEMESSAGE_H_ */
