# TCL File Generated by Component Editor 12.1
# Sat Jun 21 13:12:59 CEST 2014
# DO NOT MODIFY


# 
# carControl "carControl" v1.0
# null 2014.06.21.13:12:59
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module carControl
# 
set_module_property NAME carControl
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Car2X
set_module_property DISPLAY_NAME carControl
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL carControl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file carControl.v VERILOG PATH nios_system/carControl/synthesis/carControl.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true

add_interface_port clock_sink reset_reset_n clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true

add_interface_port reset_sink clk_clk reset_n Input 1


# 
# connection point avalon_master_1
# 
add_interface avalon_master_1 avalon start
set_interface_property avalon_master_1 addressUnits SYMBOLS
set_interface_property avalon_master_1 associatedClock clock_sink
set_interface_property avalon_master_1 associatedReset reset_sink
set_interface_property avalon_master_1 bitsPerSymbol 8
set_interface_property avalon_master_1 burstOnBurstBoundariesOnly false
set_interface_property avalon_master_1 burstcountUnits WORDS
set_interface_property avalon_master_1 doStreamReads false
set_interface_property avalon_master_1 doStreamWrites false
set_interface_property avalon_master_1 holdTime 0
set_interface_property avalon_master_1 linewrapBursts false
set_interface_property avalon_master_1 maximumPendingReadTransactions 0
set_interface_property avalon_master_1 readLatency 0
set_interface_property avalon_master_1 readWaitTime 1
set_interface_property avalon_master_1 setupTime 0
set_interface_property avalon_master_1 timingUnits Cycles
set_interface_property avalon_master_1 writeWaitTime 0
set_interface_property avalon_master_1 ENABLED true

add_interface_port avalon_master_1 carcontrol_master_readdata readdata Input 32
add_interface_port avalon_master_1 carcontrol_master_readdatavalid readdatavalid Input 1
add_interface_port avalon_master_1 carcontrol_master_burstcount burstcount Output 1
add_interface_port avalon_master_1 carcontrol_master_writedata writedata Output 32
add_interface_port avalon_master_1 carcontrol_master_address address Output 10
add_interface_port avalon_master_1 carcontrol_master_write write Output 1
add_interface_port avalon_master_1 carcontrol_master_read read Output 1
add_interface_port avalon_master_1 carcontrol_master_waitrequest waitrequest Input 1
add_interface_port avalon_master_1 carcontrol_master_byteenable byteenable Output 4
add_interface_port avalon_master_1 carcontrol_master_debugaccess chipselect Output 1

