//This header file was generated by ComBuilder on 17.03.2014 18:01:05

/**********************************************************************************
File Description:
This file contains the header of one SubMessage of the sensor ADC.
For general sensor information see '../sensors/'ADCSensor.h

All messages have to be understand by Nios2 and Linux-PC. Please use the flag
CENTRAL_ECU_BUILD to distinguish the different builds!

**********************************************************************************/


/**********************************************************************************
SubMessage Description:
Contains information about connected channels.
**********************************************************************************/

#ifndef ADCINFOMESSAGE_H_
#define ADCINFOMESSAGE_H_

// Import Interfaces
#include "CarMessage.h"

class CADCInfoMessage : public CCarMessage
{
public:
	CADCInfoMessage(alt_u8 uiChannelNumbers[]);
	CADCInfoMessage(alt_u8* pMessage, int iLength);
	virtual ~CADCInfoMessage();
	void answerMessage(alt_u8 uiChannelCount, alt_u8 uiChannelNumbers[],
			alt_u8 uiChannelAliasStrings[]);
	void doAction();
	bool getBytes(alt_u8* pMessage);
	alt_u32 getLength();

	const alt_u8* getUiChannelAliasStrings() const {
		return m_uiChannelAliasStrings;
	}

	alt_u8 getUiChannelCount() const {
		return m_uiChannelCount;
	}

	const alt_u8* getUiChannelNumbers() const {
		return m_uiChannelNumbers;
	}

private:
	alt_u8 m_uiChannelCount;
	alt_u8 m_uiChannelNumbers[2];
	alt_u8 m_uiChannelAliasStrings[14];

    void parseMessage(alt_u8 *pMessage, int iLength);

};

#endif /* ADCINFOMESSAGE_H_ */
