/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2_communication' in SOPC Builder design 'nios_system'
 * SOPC Builder design path: C:/Users/Florian/Documents/GitHub/Car2X/hardware/nios_system.sopcinfo
 *
 * Generated: Tue Jun 03 14:56:17 CEST 2014
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_qsys"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x42820
#define ALT_CPU_CPU_FREQ 100000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "small"
#define ALT_CPU_DATA_ADDR_WIDTH 0x13
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x20020
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 100000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 1
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 32
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_ICACHE_SIZE 4096
#define ALT_CPU_INST_ADDR_WIDTH 0x13
#define ALT_CPU_NAME "nios2_communication"
#define ALT_CPU_RESET_ADDR 0x20000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x42820
#define NIOS2_CPU_FREQ 100000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "small"
#define NIOS2_DATA_ADDR_WIDTH 0x13
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x20020
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 1
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 32
#define NIOS2_ICACHE_LINE_SIZE_LOG2 5
#define NIOS2_ICACHE_SIZE 4096
#define NIOS2_INST_ADDR_WIDTH 0x13
#define NIOS2_RESET_ADDR 0x20000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_MUTEX
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_SGDMA
#define __ALTERA_AVALON_TIMER
#define __ALTERA_NIOS2_QSYS
#define __TRIPLE_SPEED_ETHERNET


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone IV E"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_SYSTEM_NAME "nios_system"


/*
 * altera_iniche configuration
 *
 */

#define DHCP_CLIENT
#define INCLUDE_TCP
#define INICHE_DEFAULT_IF "NOT_USED"
#define IP_FRAGMENTS


/*
 * descriptor_memory configuration
 *
 */

#define ALT_MODULE_CLASS_descriptor_memory altera_avalon_onchip_memory2
#define DESCRIPTOR_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define DESCRIPTOR_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define DESCRIPTOR_MEMORY_BASE 0x41000
#define DESCRIPTOR_MEMORY_CONTENTS_INFO ""
#define DESCRIPTOR_MEMORY_DUAL_PORT 0
#define DESCRIPTOR_MEMORY_GUI_RAM_BLOCK_TYPE "Automatic"
#define DESCRIPTOR_MEMORY_INIT_CONTENTS_FILE "descriptor_memory"
#define DESCRIPTOR_MEMORY_INIT_MEM_CONTENT 1
#define DESCRIPTOR_MEMORY_INSTANCE_ID "NONE"
#define DESCRIPTOR_MEMORY_IRQ -1
#define DESCRIPTOR_MEMORY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DESCRIPTOR_MEMORY_NAME "/dev/descriptor_memory"
#define DESCRIPTOR_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define DESCRIPTOR_MEMORY_RAM_BLOCK_TYPE "Auto"
#define DESCRIPTOR_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"
#define DESCRIPTOR_MEMORY_SINGLE_CLOCK_OP 0
#define DESCRIPTOR_MEMORY_SIZE_MULTIPLE 1
#define DESCRIPTOR_MEMORY_SIZE_VALUE 4096u
#define DESCRIPTOR_MEMORY_SPAN 4096
#define DESCRIPTOR_MEMORY_TYPE "altera_avalon_onchip_memory2"
#define DESCRIPTOR_MEMORY_WRITABLE 1


/*
 * hal configuration
 *
 */

#define ALT_MAX_FD 32
#define ALT_SYS_CLK none
#define ALT_TIMESTAMP_CLK none


/*
 * jtag_uart_communication configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart_communication altera_avalon_jtag_uart
#define JTAG_UART_COMMUNICATION_BASE 0x43488
#define JTAG_UART_COMMUNICATION_IRQ 0
#define JTAG_UART_COMMUNICATION_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_COMMUNICATION_NAME "/dev/jtag_uart_communication"
#define JTAG_UART_COMMUNICATION_READ_DEPTH 64
#define JTAG_UART_COMMUNICATION_READ_THRESHOLD 8
#define JTAG_UART_COMMUNICATION_SPAN 8
#define JTAG_UART_COMMUNICATION_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_COMMUNICATION_WRITE_DEPTH 64
#define JTAG_UART_COMMUNICATION_WRITE_THRESHOLD 8


/*
 * main_memory_communication configuration
 *
 */

#define ALT_MODULE_CLASS_main_memory_communication altera_avalon_onchip_memory2
#define MAIN_MEMORY_COMMUNICATION_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define MAIN_MEMORY_COMMUNICATION_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define MAIN_MEMORY_COMMUNICATION_BASE 0x20000
#define MAIN_MEMORY_COMMUNICATION_CONTENTS_INFO ""
#define MAIN_MEMORY_COMMUNICATION_DUAL_PORT 0
#define MAIN_MEMORY_COMMUNICATION_GUI_RAM_BLOCK_TYPE "Automatic"
#define MAIN_MEMORY_COMMUNICATION_INIT_CONTENTS_FILE "main_memory_communication"
#define MAIN_MEMORY_COMMUNICATION_INIT_MEM_CONTENT 1
#define MAIN_MEMORY_COMMUNICATION_INSTANCE_ID "NONE"
#define MAIN_MEMORY_COMMUNICATION_IRQ -1
#define MAIN_MEMORY_COMMUNICATION_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MAIN_MEMORY_COMMUNICATION_NAME "/dev/main_memory_communication"
#define MAIN_MEMORY_COMMUNICATION_NON_DEFAULT_INIT_FILE_ENABLED 0
#define MAIN_MEMORY_COMMUNICATION_RAM_BLOCK_TYPE "Auto"
#define MAIN_MEMORY_COMMUNICATION_READ_DURING_WRITE_MODE "DONT_CARE"
#define MAIN_MEMORY_COMMUNICATION_SINGLE_CLOCK_OP 0
#define MAIN_MEMORY_COMMUNICATION_SIZE_MULTIPLE 1
#define MAIN_MEMORY_COMMUNICATION_SIZE_VALUE 102400u
#define MAIN_MEMORY_COMMUNICATION_SPAN 102400
#define MAIN_MEMORY_COMMUNICATION_TYPE "altera_avalon_onchip_memory2"
#define MAIN_MEMORY_COMMUNICATION_WRITABLE 1


/*
 * main_memory_communication configuration as viewed by sgdma_rx_m_write
 *
 */

#define SGDMA_RX_M_WRITE_MAIN_MEMORY_COMMUNICATION_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SGDMA_RX_M_WRITE_MAIN_MEMORY_COMMUNICATION_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SGDMA_RX_M_WRITE_MAIN_MEMORY_COMMUNICATION_BASE 0x20000
#define SGDMA_RX_M_WRITE_MAIN_MEMORY_COMMUNICATION_CONTENTS_INFO ""
#define SGDMA_RX_M_WRITE_MAIN_MEMORY_COMMUNICATION_DUAL_PORT 0
#define SGDMA_RX_M_WRITE_MAIN_MEMORY_COMMUNICATION_GUI_RAM_BLOCK_TYPE "Automatic"
#define SGDMA_RX_M_WRITE_MAIN_MEMORY_COMMUNICATION_INIT_CONTENTS_FILE "main_memory_communication"
#define SGDMA_RX_M_WRITE_MAIN_MEMORY_COMMUNICATION_INIT_MEM_CONTENT 1
#define SGDMA_RX_M_WRITE_MAIN_MEMORY_COMMUNICATION_INSTANCE_ID "NONE"
#define SGDMA_RX_M_WRITE_MAIN_MEMORY_COMMUNICATION_IRQ -1
#define SGDMA_RX_M_WRITE_MAIN_MEMORY_COMMUNICATION_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_RX_M_WRITE_MAIN_MEMORY_COMMUNICATION_NAME "/dev/main_memory_communication"
#define SGDMA_RX_M_WRITE_MAIN_MEMORY_COMMUNICATION_NON_DEFAULT_INIT_FILE_ENABLED 0
#define SGDMA_RX_M_WRITE_MAIN_MEMORY_COMMUNICATION_RAM_BLOCK_TYPE "Auto"
#define SGDMA_RX_M_WRITE_MAIN_MEMORY_COMMUNICATION_READ_DURING_WRITE_MODE "DONT_CARE"
#define SGDMA_RX_M_WRITE_MAIN_MEMORY_COMMUNICATION_SINGLE_CLOCK_OP 0
#define SGDMA_RX_M_WRITE_MAIN_MEMORY_COMMUNICATION_SIZE_MULTIPLE 1
#define SGDMA_RX_M_WRITE_MAIN_MEMORY_COMMUNICATION_SIZE_VALUE 102400u
#define SGDMA_RX_M_WRITE_MAIN_MEMORY_COMMUNICATION_SPAN 102400
#define SGDMA_RX_M_WRITE_MAIN_MEMORY_COMMUNICATION_TYPE "altera_avalon_onchip_memory2"
#define SGDMA_RX_M_WRITE_MAIN_MEMORY_COMMUNICATION_WRITABLE 1


/*
 * main_memory_communication configuration as viewed by sgdma_tx_m_read
 *
 */

#define SGDMA_TX_M_READ_MAIN_MEMORY_COMMUNICATION_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SGDMA_TX_M_READ_MAIN_MEMORY_COMMUNICATION_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SGDMA_TX_M_READ_MAIN_MEMORY_COMMUNICATION_BASE 0x20000
#define SGDMA_TX_M_READ_MAIN_MEMORY_COMMUNICATION_CONTENTS_INFO ""
#define SGDMA_TX_M_READ_MAIN_MEMORY_COMMUNICATION_DUAL_PORT 0
#define SGDMA_TX_M_READ_MAIN_MEMORY_COMMUNICATION_GUI_RAM_BLOCK_TYPE "Automatic"
#define SGDMA_TX_M_READ_MAIN_MEMORY_COMMUNICATION_INIT_CONTENTS_FILE "main_memory_communication"
#define SGDMA_TX_M_READ_MAIN_MEMORY_COMMUNICATION_INIT_MEM_CONTENT 1
#define SGDMA_TX_M_READ_MAIN_MEMORY_COMMUNICATION_INSTANCE_ID "NONE"
#define SGDMA_TX_M_READ_MAIN_MEMORY_COMMUNICATION_IRQ -1
#define SGDMA_TX_M_READ_MAIN_MEMORY_COMMUNICATION_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_TX_M_READ_MAIN_MEMORY_COMMUNICATION_NAME "/dev/main_memory_communication"
#define SGDMA_TX_M_READ_MAIN_MEMORY_COMMUNICATION_NON_DEFAULT_INIT_FILE_ENABLED 0
#define SGDMA_TX_M_READ_MAIN_MEMORY_COMMUNICATION_RAM_BLOCK_TYPE "Auto"
#define SGDMA_TX_M_READ_MAIN_MEMORY_COMMUNICATION_READ_DURING_WRITE_MODE "DONT_CARE"
#define SGDMA_TX_M_READ_MAIN_MEMORY_COMMUNICATION_SINGLE_CLOCK_OP 0
#define SGDMA_TX_M_READ_MAIN_MEMORY_COMMUNICATION_SIZE_MULTIPLE 1
#define SGDMA_TX_M_READ_MAIN_MEMORY_COMMUNICATION_SIZE_VALUE 102400u
#define SGDMA_TX_M_READ_MAIN_MEMORY_COMMUNICATION_SPAN 102400
#define SGDMA_TX_M_READ_MAIN_MEMORY_COMMUNICATION_TYPE "altera_avalon_onchip_memory2"
#define SGDMA_TX_M_READ_MAIN_MEMORY_COMMUNICATION_WRITABLE 1


/*
 * mutex_shared_memory configuration
 *
 */

#define ALT_MODULE_CLASS_mutex_shared_memory altera_avalon_mutex
#define MUTEX_SHARED_MEMORY_BASE 0x43480
#define MUTEX_SHARED_MEMORY_IRQ -1
#define MUTEX_SHARED_MEMORY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MUTEX_SHARED_MEMORY_NAME "/dev/mutex_shared_memory"
#define MUTEX_SHARED_MEMORY_OWNER_INIT 0
#define MUTEX_SHARED_MEMORY_OWNER_WIDTH 16
#define MUTEX_SHARED_MEMORY_SPAN 8
#define MUTEX_SHARED_MEMORY_TYPE "altera_avalon_mutex"
#define MUTEX_SHARED_MEMORY_VALUE_INIT 0
#define MUTEX_SHARED_MEMORY_VALUE_WIDTH 16


/*
 * sgdma_rx configuration
 *
 */

#define ALT_MODULE_CLASS_sgdma_rx altera_avalon_sgdma
#define SGDMA_RX_ADDRESS_WIDTH 32
#define SGDMA_RX_ALWAYS_DO_MAX_BURST 1
#define SGDMA_RX_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define SGDMA_RX_AVALON_MM_BYTE_REORDER_MODE 0
#define SGDMA_RX_BASE 0x43400
#define SGDMA_RX_BURST_DATA_WIDTH 8
#define SGDMA_RX_BURST_TRANSFER 0
#define SGDMA_RX_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define SGDMA_RX_CHAIN_WRITEBACK_DATA_WIDTH 32
#define SGDMA_RX_COMMAND_FIFO_DATA_WIDTH 104
#define SGDMA_RX_CONTROL_DATA_WIDTH 8
#define SGDMA_RX_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define SGDMA_RX_CONTROL_SLAVE_DATA_WIDTH 32
#define SGDMA_RX_DESCRIPTOR_READ_BURST 0
#define SGDMA_RX_DESC_DATA_WIDTH 32
#define SGDMA_RX_HAS_READ_BLOCK 0
#define SGDMA_RX_HAS_WRITE_BLOCK 1
#define SGDMA_RX_IN_ERROR_WIDTH 6
#define SGDMA_RX_IRQ 1
#define SGDMA_RX_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SGDMA_RX_NAME "/dev/sgdma_rx"
#define SGDMA_RX_OUT_ERROR_WIDTH 0
#define SGDMA_RX_READ_BLOCK_DATA_WIDTH 32
#define SGDMA_RX_READ_BURSTCOUNT_WIDTH 4
#define SGDMA_RX_SPAN 64
#define SGDMA_RX_STATUS_TOKEN_DATA_WIDTH 24
#define SGDMA_RX_STREAM_DATA_WIDTH 32
#define SGDMA_RX_SYMBOLS_PER_BEAT 4
#define SGDMA_RX_TYPE "altera_avalon_sgdma"
#define SGDMA_RX_UNALIGNED_TRANSFER 0
#define SGDMA_RX_WRITE_BLOCK_DATA_WIDTH 32
#define SGDMA_RX_WRITE_BURSTCOUNT_WIDTH 4


/*
 * sgdma_tx configuration
 *
 */

#define ALT_MODULE_CLASS_sgdma_tx altera_avalon_sgdma
#define SGDMA_TX_ADDRESS_WIDTH 32
#define SGDMA_TX_ALWAYS_DO_MAX_BURST 1
#define SGDMA_TX_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define SGDMA_TX_AVALON_MM_BYTE_REORDER_MODE 0
#define SGDMA_TX_BASE 0x43440
#define SGDMA_TX_BURST_DATA_WIDTH 8
#define SGDMA_TX_BURST_TRANSFER 0
#define SGDMA_TX_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define SGDMA_TX_CHAIN_WRITEBACK_DATA_WIDTH 32
#define SGDMA_TX_COMMAND_FIFO_DATA_WIDTH 104
#define SGDMA_TX_CONTROL_DATA_WIDTH 8
#define SGDMA_TX_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define SGDMA_TX_CONTROL_SLAVE_DATA_WIDTH 32
#define SGDMA_TX_DESCRIPTOR_READ_BURST 0
#define SGDMA_TX_DESC_DATA_WIDTH 32
#define SGDMA_TX_HAS_READ_BLOCK 1
#define SGDMA_TX_HAS_WRITE_BLOCK 0
#define SGDMA_TX_IN_ERROR_WIDTH 0
#define SGDMA_TX_IRQ 2
#define SGDMA_TX_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SGDMA_TX_NAME "/dev/sgdma_tx"
#define SGDMA_TX_OUT_ERROR_WIDTH 1
#define SGDMA_TX_READ_BLOCK_DATA_WIDTH 32
#define SGDMA_TX_READ_BURSTCOUNT_WIDTH 4
#define SGDMA_TX_SPAN 64
#define SGDMA_TX_STATUS_TOKEN_DATA_WIDTH 24
#define SGDMA_TX_STREAM_DATA_WIDTH 32
#define SGDMA_TX_SYMBOLS_PER_BEAT 4
#define SGDMA_TX_TYPE "altera_avalon_sgdma"
#define SGDMA_TX_UNALIGNED_TRANSFER 0
#define SGDMA_TX_WRITE_BLOCK_DATA_WIDTH 32
#define SGDMA_TX_WRITE_BURSTCOUNT_WIDTH 4


/*
 * shared_memory configuration
 *
 */

#define ALT_MODULE_CLASS_shared_memory altera_avalon_onchip_memory2
#define SHARED_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SHARED_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SHARED_MEMORY_BASE 0x40000
#define SHARED_MEMORY_CONTENTS_INFO ""
#define SHARED_MEMORY_DUAL_PORT 1
#define SHARED_MEMORY_GUI_RAM_BLOCK_TYPE "Automatic"
#define SHARED_MEMORY_INIT_CONTENTS_FILE "shared_memory"
#define SHARED_MEMORY_INIT_MEM_CONTENT 1
#define SHARED_MEMORY_INSTANCE_ID "NONE"
#define SHARED_MEMORY_IRQ -1
#define SHARED_MEMORY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SHARED_MEMORY_NAME "/dev/shared_memory"
#define SHARED_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define SHARED_MEMORY_RAM_BLOCK_TYPE "Auto"
#define SHARED_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"
#define SHARED_MEMORY_SINGLE_CLOCK_OP 1
#define SHARED_MEMORY_SIZE_MULTIPLE 1
#define SHARED_MEMORY_SIZE_VALUE 4096u
#define SHARED_MEMORY_SPAN 4096
#define SHARED_MEMORY_TYPE "altera_avalon_onchip_memory2"
#define SHARED_MEMORY_WRITABLE 1


/*
 * timer_0 configuration
 *
 */

#define ALT_MODULE_CLASS_timer_0 altera_avalon_timer
#define TIMER_0_ALWAYS_RUN 1
#define TIMER_0_BASE 0x0
#define TIMER_0_COUNTER_SIZE 32
#define TIMER_0_FIXED_PERIOD 1
#define TIMER_0_FREQ 100000000u
#define TIMER_0_IRQ 3
#define TIMER_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_0_LOAD_VALUE 999999ull
#define TIMER_0_MULT 0.0010
#define TIMER_0_NAME "/dev/timer_0"
#define TIMER_0_PERIOD 10
#define TIMER_0_PERIOD_UNITS "ms"
#define TIMER_0_RESET_OUTPUT 0
#define TIMER_0_SNAPSHOT 0
#define TIMER_0_SPAN 32
#define TIMER_0_TICKS_PER_SEC 100u
#define TIMER_0_TIMEOUT_PULSE_OUTPUT 0
#define TIMER_0_TYPE "altera_avalon_timer"


/*
 * tse_mac configuration
 *
 */

#define ALT_MODULE_CLASS_tse_mac triple_speed_ethernet
#define TSE_MAC_BASE 0x43000
#define TSE_MAC_ENABLE_MACLITE 0
#define TSE_MAC_FIFO_WIDTH 32
#define TSE_MAC_IRQ -1
#define TSE_MAC_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TSE_MAC_IS_MULTICHANNEL_MAC 0
#define TSE_MAC_MACLITE_GIGE 0
#define TSE_MAC_MDIO_SHARED 0
#define TSE_MAC_NAME "/dev/tse_mac"
#define TSE_MAC_NUMBER_OF_CHANNEL 1
#define TSE_MAC_NUMBER_OF_MAC_MDIO_SHARED 1
#define TSE_MAC_PCS 0
#define TSE_MAC_PCS_ID 0u
#define TSE_MAC_PCS_SGMII 0
#define TSE_MAC_RECEIVE_FIFO_DEPTH 2048
#define TSE_MAC_REGISTER_SHARED 0
#define TSE_MAC_RGMII 1
#define TSE_MAC_SPAN 1024
#define TSE_MAC_TRANSMIT_FIFO_DEPTH 2048
#define TSE_MAC_TYPE "triple_speed_ethernet"
#define TSE_MAC_UNASSIGNED "unassigned"
#define TSE_MAC_USE_MDIO 1


/*
 * ucosii configuration
 *
 */

#define OS_ARG_CHK_EN 1
#define OS_CPU_HOOKS_EN 1
#define OS_DEBUG_EN 1
#define OS_EVENT_NAME_SIZE 32
#define OS_FLAGS_NBITS 16
#define OS_FLAG_ACCEPT_EN 1
#define OS_FLAG_DEL_EN 1
#define OS_FLAG_EN 1
#define OS_FLAG_NAME_SIZE 32
#define OS_FLAG_QUERY_EN 1
#define OS_FLAG_WAIT_CLR_EN 1
#define OS_LOWEST_PRIO 20
#define OS_MAX_EVENTS 60
#define OS_MAX_FLAGS 20
#define OS_MAX_MEM_PART 60
#define OS_MAX_QS 20
#define OS_MAX_TASKS 10
#define OS_MBOX_ACCEPT_EN 1
#define OS_MBOX_DEL_EN 1
#define OS_MBOX_EN 1
#define OS_MBOX_POST_EN 1
#define OS_MBOX_POST_OPT_EN 1
#define OS_MBOX_QUERY_EN 1
#define OS_MEM_EN 1
#define OS_MEM_NAME_SIZE 32
#define OS_MEM_QUERY_EN 1
#define OS_MUTEX_ACCEPT_EN 1
#define OS_MUTEX_DEL_EN 1
#define OS_MUTEX_EN 1
#define OS_MUTEX_QUERY_EN 1
#define OS_Q_ACCEPT_EN 1
#define OS_Q_DEL_EN 1
#define OS_Q_EN 1
#define OS_Q_FLUSH_EN 1
#define OS_Q_POST_EN 1
#define OS_Q_POST_FRONT_EN 1
#define OS_Q_POST_OPT_EN 1
#define OS_Q_QUERY_EN 1
#define OS_SCHED_LOCK_EN 1
#define OS_SEM_ACCEPT_EN 1
#define OS_SEM_DEL_EN 1
#define OS_SEM_EN 1
#define OS_SEM_QUERY_EN 1
#define OS_SEM_SET_EN 1
#define OS_TASK_CHANGE_PRIO_EN 1
#define OS_TASK_CREATE_EN 1
#define OS_TASK_CREATE_EXT_EN 1
#define OS_TASK_DEL_EN 1
#define OS_TASK_IDLE_STK_SIZE 512
#define OS_TASK_NAME_SIZE 32
#define OS_TASK_PROFILE_EN 1
#define OS_TASK_QUERY_EN 1
#define OS_TASK_STAT_EN 1
#define OS_TASK_STAT_STK_CHK_EN 1
#define OS_TASK_STAT_STK_SIZE 512
#define OS_TASK_SUSPEND_EN 1
#define OS_TASK_SW_HOOK_EN 1
#define OS_TASK_TMR_PRIO 0
#define OS_TASK_TMR_STK_SIZE 512
#define OS_THREAD_SAFE_NEWLIB 1
#define OS_TICK_STEP_EN 1
#define OS_TIME_DLY_HMSM_EN 1
#define OS_TIME_DLY_RESUME_EN 1
#define OS_TIME_GET_SET_EN 1
#define OS_TIME_TICK_HOOK_EN 1
#define OS_TMR_CFG_MAX 16
#define OS_TMR_CFG_NAME_SIZE 16
#define OS_TMR_CFG_TICKS_PER_SEC 10
#define OS_TMR_CFG_WHEEL_SIZE 2
#define OS_TMR_EN 0

#endif /* __SYSTEM_H_ */
